name: Copy all Files to Another Folder

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN_NO_1}}

    - name: Copy Files
      run: |
        
        cp -R ./practice-github-actions/dir1/* ./practice-github-actions/dir2/
    - name: Add Delay
      run: sleep 15  # Adjust the delay time as needed

    - name: Commit and Push Changes
      run: |
        git config --local user.email "abc@example.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Copy files to destination_folder"
        git push