name: Copy all Files to Another Folder

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN_NO_1}}

    - name: Copy Files
      run: |
        
        rsync -r --ignore-existing ./practice-github-actions/dir1/ ./practice-github-actions/dir2/  # Replace 'source_folder' with the folder containing files to copy

    - name: Display Newly Copied Files
      run: |
        echo "Newly copied files to dir2"
        diff -rq ./practice-github-actions/dir1/ ./practice-github-actions/dir2/ | grep "Only in ./practice-github-actions/dir2/" | sed 's/Only in ./practice-github-actions/dir2/ //'
        - name: Add Delay
    - name: Commit and Push Changes
      run: |
        git config --local user.email "abc@example.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Copy files to destination_folder"
        git push